name: Continuous Inspection

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
inspection:
name: Code Inspection
runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: 3.11

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install flake8 bandit

  - name: Run flake8 (Linting)
    run: flake8 src/

  - name: Run bandit (Security Check)
    run: bandit -r src/
